version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 5000
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 2703:2703
    volumes:
      - mongodb:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
volumes:
 mongodb: