version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 5000
    volumes:
      - ./:/code
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
volumes:
 mongodb: